
public class Processes {
	public static String message = "; generated by SpeedTest\n; Process: %s\n\n";

	public static String test_squares_crosses(Machine machine) {
//		float[] speeds = { 50, 100, 150, 200 };
		float[] speeds = { 200 };

		String output = "";

		output += String.format(message, "test_proc_1");

		output += Gcodes.home();
		output += Gcodes.move_z(15);
		output += "\n";

		for (int i = 0; i < speeds.length; i++) {
			output += Movements.squares_crosses_cw(machine, 3, speeds[i], machine.DEFAULT_ACCEL);
		}

		return output;
	}

	public static String test_circles(Machine machine) {
//		float[] speeds = { 50, 100, 150, 200 };
		float[] speeds = { 25.0f, 37.5f, 50.0f, 75.0f, 100.0f };

		String output = "";

		output += String.format(message, "test_proc_1");

		output += Gcodes.home();
		output += Gcodes.move_z(15);
		output += "\n";

		for (int i = 0; i < speeds.length; i++) {
			output += Movements.circles_cw(machine, 1, speeds[i], machine.DEFAULT_ACCEL);
		}

		return output;
	}
}
