
public class Processes {
	public static String message = "; generated by SpeedTest\n; Process: %s\n\n";
	
	public static String test_proc_1(Machine machine) {
		float[] speeds = { 50, 100, 150, 200 };
		
		String output = "";
		
		output += String.format(message, "test_proc_1");
		
		output += Gcodes.home();
		output += Gcodes.move_z(15);
		output += "\n";
		
		for (int i = 0; i < speeds.length; i++) {
			output += Movements.squares_cw(machine, 8, speeds[i], machine.DEFAULT_ACCEL);
		}
		
		return output;
	}
}
